### ISSUE TITLE
What happens if user clears the app data??

### ISSUE THREAD

**Issue by tuhin10** [tslamic/premiumer#10]
What happens if user clears the app data? Does he/she have to buy the app again?

**Comment by tslamic** [comment]
If you check the source, you'll see that Play services are used in order to determine if an item has been purchased or not, which ensures a _premium_ user will never see ads, even if local cache is cleared:

```
  @VisibleForTesting boolean checkAds() {
    return exec(new Runnable() {
      @Override public void run() {
        final boolean owns = billing.ownsSku(sku);
        final int id = owns ? PremiumerHandler.ON_HIDE_ADS : PremiumerHandler.ON_SHOW_ADS;
        handler.obtainMessage(id).sendToTarget();
      }
    });
  }
```

However, if a user decides to consume (cancel) the purchase, then `Premiumer#consumeSku` method will be invoked. This method does refers to the local cache for all the required purchase data. If not present, then cancellation obviously won't work.

What happens with your cache when a user clears the data depends on the `PurchaseCache` you're using. If it's the default `SharedPrefsCache`, you might want to check out either [Key/Value Backup](https://developer.android.com/guide/topics/data/keyvaluebackup.html) or [AutoBackup](https://developer.android.com/guide/topics/data/autobackup.html), depending on your SDK version. If you're using a custom `PurchaseCache`, this is entirely up to you (the above links might help).
